<?php
final class Senoobar_Theme {
    private static $instance=null;
    public static function get_instance(){if(null===self::$instance)self::$instance=new self();return self::$instance;}
    private function __construct(){}
    public function init(){$this->setup();$this->assets();$this->woo();$this->menus();$this->customizer();$this->pwa();$this->perf();}
    private function setup(){add_theme_support('title-tag');add_theme_support('post-thumbnails');add_theme_support('custom-logo',['height'=>60,'width'=>180,'flex-height'=>true,'flex-width'=>true]);add_theme_support('html5',['search-form','comment-form','comment-list','gallery','caption','style','script']);add_theme_support('responsive-embeds');add_theme_support('wp-block-styles');add_theme_support('align-wide');add_image_size('senoobar-product-thumb',400,400,true);add_image_size('senoobar-product-medium',600,600,true);add_image_size('senoobar-product-large',1200,800,true);add_image_size('senoobar-hero',800,1000,true);}
    private function menus(){register_nav_menus(['primary'=>__('منوی اصلی','senoobar'),'footer'=>__('منوی فوتر','senoobar')]);}
    private function woo(){if(!class_exists('WooCommerce'))return;add_theme_support('woocommerce');add_theme_support('wc-product-gallery-zoom');add_theme_support('wc-product-gallery-lightbox');add_theme_support('wc-product-gallery-slider');add_filter('woocommerce_enqueue_styles','__return_empty_array');add_filter('woocommerce_add_to_cart_fragments',function($f){ob_start();echo '<span class="cart-count">'.WC()->cart->get_cart_contents_count().'</span>';$f['.cart-count']=ob_get_clean();return $f;});}
    private function pwa(){add_action('wp_head',function(){echo '<meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-title" content="صنوبر"><link rel="apple-touch-icon" href="'.SENOOBAR_URI.'/assets/images/logo.png">';});}
    private function perf(){remove_action('wp_head','print_emoji_detection_script',7);remove_action('wp_print_styles','print_emoji_styles');add_filter('script_loader_tag',function($t,$h){if(in_array($h,['senoobar-app','senoobar-push']))return str_replace(' src',' defer src',$t);return $t;},10,2);}
    private function customizer(){add_action('customize_register',function($c){$c->add_setting('senoobar_announcement',['default'=>'ارسال رایگان']);$c->add_control('senoobar_announcement',['label'=>'متن نوار اعلان','section'=>'title_tagline','type'=>'text']);$c->add_section('senoobar_hero',['title'=>'هیرو','priority'=>30]);$c->add_setting('senoobar_hero_title',['default'=>'زیبایی در سادگی']);$c->add_control('senoobar_hero_title',['label'=>'عنوان','section'=>'senoobar_hero','type'=>'text']);$c->add_setting('senoobar_hero_subtitle',['default'=>'مبلمان خانه']);$c->add_control('senoobar_hero_subtitle',['label'=>'زیرعنوان','section'=>'senoobar_hero','type'=>'textarea']);foreach(['senoobar_hero_img1'=>'تصویر اول','senoobar_hero_img2'=>'تصویر دوم'] as $id=>$l){$c->add_setting($id);$c->add_control(new WP_Customize_Media_Control($c,$id,['label'=>$l,'section'=>'senoobar_hero']));}$c->add_section('senoobar_promo',['title'=>'بنرها','priority'=>35]);foreach(['senoobar_promo_img1'=>'بنر ۱','senoobar_promo_img2'=>'بنر ۲'] as $id=>$l){$c->add_setting($id);$c->add_control(new WP_Customize_Media_Control($c,$id,['label'=>$l,'section'=>'senoobar_promo']));}$c->add_section('senoobar_gallery',['title'=>'گالری','priority'=>40]);for($i=1;$i<=8;$i++){$c->add_setting("senoobar_gallery_img{$i}");$c->add_control(new WP_Customize_Media_Control($c,"senoobar_gallery_img{$i}",['label'=>"تصویر {$i}",'section'=>'senoobar_gallery']));}$c->add_setting('senoobar_video_thumb');$c->add_control(new WP_Customize_Media_Control($c,'senoobar_video_thumb',['label'=>'تصویر ویدیو','section'=>'senoobar_hero']));});}
    private function assets(){add_action('wp_enqueue_scripts',function(){wp_enqueue_style('senoobar-critical',SENOOBAR_URI.'/assets/css/critical.css',[],SENOOBAR_VERSION);wp_enqueue_style('senoobar-main',SENOOBAR_URI.'/assets/css/main.css',[],SENOOBAR_VERSION);if(is_rtl())wp_enqueue_style('senoobar-rtl',SENOOBAR_URI.'/assets/css/rtl.css',['senoobar-main'],SENOOBAR_VERSION);wp_enqueue_script('senoobar-app',SENOOBAR_URI.'/assets/js/app.js',[],SENOOBAR_VERSION,true);wp_localize_script('senoobar-app','senoobarData',['ajaxUrl'=>admin_url('admin-ajax.php'),'cartUrl'=>wc_get_cart_url(),'isRTL'=>is_rtl(),'siteUrl'=>home_url()]);});}
}